/**
 * Auth Action Types
 */
export const AUTO_LOGIN_ERROR = "AUTH/AUTO_LOGIN_ERROR";
export const SIGNUP_REQUEST = "AUTH/SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "AUTH/SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "AUTH/SIGNUP_ERROR";
export const LOGIN_REQUEST = "AUTH/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS";
export const LOGIN_ERROR = "AUTH/LOGIN_ERROR";
export const FETCH_PROFILE_REQUEST = "AUTH/FETCH_PROFILE_REQUEST";
export const FETCH_PROFILE_SUCCESS = "AUTH/FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_ERROR = "AUTH/FETCH_PROFILE_ERROR";
export const LOGOUT = "AUTH/LOGOUT";
/**
 * Posts Action Types
 */
export const POSTS_FETCH_REQUEST = "POSTS/POSTS_FETCH_REQUEST";
export const POSTS_FETCH_SUCCESS = "POSTS/POSTS_FETCH_SUCCESS";
export const POSTS_FETCH_ERROR = "POSTS/POSTS_FETCH_ERROR";
export const POSTS_ADD_REQUEST = "POSTS/POSTS_ADD_REQUEST";
export const POSTS_ADD_SUCCESS = "POSTS/POSTS_ADD_SUCCESS";
export const POSTS_ADD_ERROR = "POSTS/POSTS_ADD_ERROR";
export const POSTS_UPDATE_REQUEST = "POSTS/POSTS_UPDATE_REQUEST";
export const POSTS_UPDATE_SUCCESS = "POSTS/POSTS_UPDATE_SUCCESS";
export const POSTS_UPDATE_ERROR = "POSTS/POSTS_UPDATE_ERROR";
export const POSTS_REMOVE_REQUEST = "POSTS/POSTS_REMOVE_REQUEST";
export const POSTS_REMOVE_SUCCESS = "POSTS/POSTS_REMOVE_SUCCESS";
export const POSTS_REMOVE_ERROR = "POSTS/POSTS_REMOVE_ERROR";
/**
 * Users Action Types
 */
export const USERS_FETCH_REQUEST = "USERS/USERS_FETCH_REQUEST";
export const USERS_FETCH_SUCCESS = "USERS/USERS_FETCH_SUCCESS";
export const USERS_FETCH_ERROR = "USERS/USERS_FETCH_ERROR";
export const USERS_ADD_REQUEST = "USERS/USERS_ADD_REQUEST";
export const USERS_ADD_SUCCESS = "USERS/USERS_ADD_SUCCESS";
export const USERS_ADD_ERROR = "USERS/USERS_ADD_ERROR";
export const USERS_UPDATE_REQUEST = "USERS/USERS_UPDATE_REQUEST";
export const USERS_UPDATE_SUCCESS = "USERS/USERS_UPDATE_SUCCESS";
export const USERS_UPDATE_ERROR = "USERS/USERS_UPDATE_ERROR";
export const USERS_REMOVE_REQUEST = "USERS/USERS_REMOVE_REQUEST";
export const USERS_REMOVE_SUCCESS = "USERS/USERS_REMOVE_SUCCESS";
export const USERS_REMOVE_ERROR = "USERS/USERS_REMOVE_ERROR";
